stages:
  - build
  - test
  - publish

build:
  stage: build
  script:
    - |
      dotnet build --configuration Release
      gci -recurse -include "Selenium.Spotfire*.nupkg" | % {
        write-host "Signing $_"
        d:\nuget\nuget sign $_ -certificatePath d:\nuget\SpotfireCodeSigning.pfx -certificatePassword $certificatePassword -timestamper http://timestamp.digicert.com
      }
  artifacts:
    paths: 
    - ./**/Selenium.Spotfire*.nupkg

test:
  stage: test
  allow_failure: true
  script:
    - dotnet test "--settings:$runSettings" --results-directory ./test-results
  artifacts:
    when: always
    paths: 
    - test-results

publish:
  stage: publish
  when: manual
  dependencies:
    - build
  script:
    - dotnet nuget push **/Selenium.Spotfire*.nupkg --api-key $NuGetAPIKey --source https://api.nuget.org/v3/index.json